create table if not exists public.lotto_draw_logs (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  ticket_count integer not null,
  tickets jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists lotto_draw_logs_created_at_idx
  on public.lotto_draw_logs (created_at desc);

create index if not exists lotto_draw_logs_ip_address_idx
  on public.lotto_draw_logs (ip_address);

alter table public.lotto_draw_logs enable row level security; 